version: "3.8"
services:
  core:
    container_name: measuresoftgram-core
    build: .
    ports:
      - "7000:5000"
    volumes:
      - ./src:/code/src
      - ./server.py:/code/server.py
    restart: on-failure
    networks:
      - measuresoftgram
    environment:
      - DEBUG=True


networks:
  measuresoftgram:
    external: true
