# This is a basic workflow to help you get started with Actions

name: Run Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
          cache: pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: |
          pip install coverage
          pip install pytest
          coverage run -m pytest tests --junitxml=./junit.xml
          coverage xml -o coverage.xml

      - name: fix code coverage paths
        if: always()
        run: |
          sed -i 's/\/home\/runner\/work\/2022-1-MeasureSoftGram-Core\/2022-1-MeasureSoftGram-Core\//\/github\/workspace\//g' coverage.xml

      - name: SonarCloud Scan
        if: always()
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: 2022-1-MeasureSoftGram-Core
          verbose: true
